
[boots]
	enable = true

	[[boots.attributes]]
		type = "generic.movement_speed"

		[boots.attributes.eneng]
			enable = true
			value = [0.03, 0.05]

		[[boots.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 0.01
			speed = 2

		[[boots.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.02

	[[boots.attributes]]
		type = "dodge_chance"

		[boots.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[boots.attributes.grow]]
			range = [1, 8]
			type = "fixed"
			value = 0.02
			speed = 2

		[[boots.attributes.grow]]
			range = [9, -1]
			type = "proportional"
			value = 0.01

	[[boots.attributes]]
		type = "generic.max_health"

		[boots.attributes.eneng]
			enable = true
			value = [2.0, 4.0]

		[[boots.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 1.0
			speed = 1

		[[boots.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[boots.attributes]]
		type = "generic.armor"

		[boots.attributes.eneng]
			enable = true
			value = [1.0, 3.0]

		[[boots.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 0.5
			speed = 1

		[[boots.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.02

	[[boots.attributes]]
		type = "generic.knockback_resistance"

		[boots.attributes.eneng]
			enable = true
			value = [0.0, 0.1]

		[[boots.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.02
			speed = 1

		[[boots.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.01

