
[bow]
	enable = true

	[[bow.attributes]]
		type = "arrow_damage"

		[bow.attributes.eneng]
			enable = true
			value = [5.0, 10.0]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 2.0
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.1

	[[bow.attributes]]
		type = "arrow_velocity"

		[bow.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.2
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[bow.attributes]]
		type = "draw_speed"

		[bow.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.1
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[bow.attributes]]
		type = "crit_chance"

		[bow.attributes.eneng]
			enable = true
			value = [0.05, 0.2]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.03
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.01

	[[bow.attributes]]
		type = "crit_damage"

		[bow.attributes.eneng]
			enable = true
			value = [1.5, 2.5]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.1
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[bow.attributes]]
		type = "generic.attack_knockback"

		[bow.attributes.eneng]
			enable = true
			value = [0.1, 0.3]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.05
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[bow.attributes]]
		type = "fire_damage"

		[bow.attributes.eneng]
			enable = true
			value = [0.5, 2.0]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.2
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.1

	[[bow.attributes]]
		type = "life_steal"

		[bow.attributes.eneng]
			enable = true
			value = [0.01, 0.05]

		[[bow.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.01
			speed = 1

		[[bow.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.005

