
[bow]
	enable = true

	[[bow.attributes]]
		type = "arrow_damage"

		[bow.attributes.eneng]
			enable = true
			value = [2.5, 5]

		[[bow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 1.5
			speed = 1

		[[bow.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.1

	[[bow.attributes]]
		type = "arrow_velocity"

		[bow.attributes.eneng]
			enable = true
			value = [0.1, 0.2]

		[[bow.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.02
			speed = 1

	[[bow.attributes]]
		type = "draw_speed"

		[bow.attributes.eneng]
			enable = true
			value = [0.1, 0.2]

		[[bow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.1
			speed = 1

		[[bow.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[bow.attributes]]
		type = "crit_chance"

		[bow.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[bow.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.02
			speed = 2

	[[bow.attributes]]
		type = "crit_damage"

		[bow.attributes.eneng]
			enable = true
			value = [0.2, 0.4]

		[[bow.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.1
			speed = 2

	[[bow.attributes]]
		type = "generic.attack_knockback"

		[bow.attributes.eneng]
			enable = true
			value = [0.1, 0.25]

		[[bow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.04
			speed = 1

	[[bow.attributes]]
		type = "life_steal"

		[[bow.attributes.grows]]
			range = [10, -1]
			type = "fixed"
			value = 0.01
			speed = 1

