
[chestplate]
	enable = true

	[[chestplate.attributes]]
		type = "generic.armor"

		[chestplate.attributes.eneng]
			enable = true
			value = [2.5, 3.0]

		[[chestplate.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.7
			speed = 1

		[[chestplate.attributes.grows]]
			range = [11, -1]
			type = "proportional"
			value = 0.05

	[[chestplate.attributes]]
		type = "generic.armor_toughness"

		[chestplate.attributes.eneng]
			enable = true
			value = [2.0, 4.0]

		[[chestplate.attributes.grows]]
			range = [1, 8]
			type = "fixed"
			value = 0.5
			speed = 2

		[[chestplate.attributes.grows]]
			range = [9, -1]
			type = "proportional"
			value = 0.02

	[[chestplate.attributes]]
		type = "generic.knockback_resistance"

		[chestplate.attributes.eneng]
			enable = true
			value = [0.1, 0.3]

		[[chestplate.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.05
			speed = 1

		[[chestplate.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[chestplate.attributes]]
		type = "generic.max_health"

		[chestplate.attributes.eneng]
			enable = true
			value = [2.4, 3.6]

		[[chestplate.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.9
			speed = 1

		[[chestplate.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

