
[chestplate]
	enable = true

	[[chestplate.attributes]]
		type = "generic.armor"

		[chestplate.attributes.eneng]
			enable = true
			value = [5.0, 7.0]

		[[chestplate.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 1.0
			speed = 1

		[[chestplate.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.05

	[[chestplate.attributes]]
		type = "generic.armor_toughness"

		[chestplate.attributes.eneng]
			enable = true
			value = [2.0, 4.0]

		[[chestplate.attributes.grow]]
			range = [1, 8]
			type = "fixed"
			value = 0.5
			speed = 2

		[[chestplate.attributes.grow]]
			range = [9, -1]
			type = "proportional"
			value = 0.02

	[[chestplate.attributes]]
		type = "generic.max_health"

		[chestplate.attributes.eneng]
			enable = true
			value = [3.0, 6.0]

		[[chestplate.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 1.0
			speed = 1

		[[chestplate.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[chestplate.attributes]]
		type = "prot_pierce"

		[chestplate.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[chestplate.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.01
			speed = 1

		[[chestplate.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

