
[crossbow]
	enable = true

	[[crossbow.attributes]]
		type = "arrow_damage"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.16, 0.37]

		[[crossbow.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.08
			speed = 1

	[[crossbow.attributes]]
		type = "draw_speed"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.16, 0.34]

		[[crossbow.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.082
			speed = 1

		[[crossbow.attributes.grows]]
			range = [11, -1]
			type = "proportional"
			value = 0.131

	[[crossbow.attributes]]
		type = "arrow_velocity"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.13, 0.26]

		[[crossbow.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.092
			speed = 1

		[[crossbow.attributes.grows]]
			range = [11, -1]
			type = "fixed"
			value = 0.12
			speed = 1

	[[crossbow.attributes]]
		type = "crit_chance"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.042, 0.072]

		[[crossbow.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.017
			speed = 2

		[[crossbow.attributes.grows]]
			range = [11, 30]
			type = "fixed"
			value = 0.033
			speed = 2

	[[crossbow.attributes]]
		type = "crit_damage"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.17, 0.36]

		[[crossbow.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.092
			speed = 2

	[[crossbow.attributes]]
		type = "generic.attack_knockback"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.1, 0.25]

		[[crossbow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.028
			speed = 1

	[[crossbow.attributes]]
		type = "life_steal"

		[[crossbow.attributes.grows]]
			range = [3, -1]
			type = "fixed"
			value = 0.021
			speed = 2

