
[crossbow]
	enable = true

	[[crossbow.attributes]]
		type = "arrow_damage"

		[crossbow.attributes.eneng]
			enable = true
			value = [7.0, 12.0]

		[[crossbow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 3.0
			speed = 1

		[[crossbow.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.1

	[[crossbow.attributes]]
		type = "draw_speed"

		[crossbow.attributes.eneng]
			enable = true
			value = [1.5, 3.0]

		[[crossbow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.2
			speed = 1

		[[crossbow.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[crossbow.attributes]]
		type = "arrow_velocity"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.1, 0.2]

		[[crossbow.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.02
			speed = 1

	[[crossbow.attributes]]
		type = "crit_chance"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.05, 0.25]

		[[crossbow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.05
			speed = 1

		[[crossbow.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.01

	[[crossbow.attributes]]
		type = "crit_damage"

		[crossbow.attributes.eneng]
			enable = true
			value = [1.5, 3.0]

		[[crossbow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.15
			speed = 1

		[[crossbow.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[crossbow.attributes]]
		type = "generic.attack_knockback"

		[crossbow.attributes.eneng]
			enable = true
			value = [0.1, 0.25]

		[[crossbow.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.04
			speed = 1

	[[crossbow.attributes]]
		type = "life_steal"

		[[crossbow.attributes.grows]]
			range = [10, -1]
			type = "fixed"
			value = 0.01
			speed = 1

