
[fishing_rod]
	enable = true

	[[fishing_rod.attributes]]
		type = "generic.luck"

		[fishing_rod.attributes.eneng]
			enable = true
			value = [1.0, 3.0]

		[[fishing_rod.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 1

		[[fishing_rod.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.1

	[[fishing_rod.attributes]]
		type = "experience_gained"

		[fishing_rod.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[fishing_rod.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.2
			speed = 1

		[[fishing_rod.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

