
[helmet]
	enable = true

	[[helmet.attributes]]
		type = "generic.armor"

		[helmet.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[helmet.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.3
			speed = 1

		[[helmet.attributes.grows]]
			range = [11, -1]
			type = "proportional"
			value = 0.02

	[[helmet.attributes]]
		type = "generic.armor_toughness"

		[helmet.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[helmet.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 2

		[[helmet.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[helmet.attributes]]
		type = "generic.max_health"

		[helmet.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[helmet.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 1

		[[helmet.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[helmet.attributes]]
		type = "dodge_chance"

		[helmet.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[helmet.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.02
			speed = 1

		[[helmet.attributes.grows]]
			range = [6, 30]
			type = "proportional"
			value = 0.05
			speed = 2

	[[helmet.attributes]]
		type = "healing_received"

		[helmet.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[helmet.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.036
			speed = 1

		[[helmet.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[helmet.attributes]]
		type = "experience_gained"

		[helmet.attributes.eneng]
			enable = true
			value = [0.03, 0.07]

		[[helmet.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.02
			speed = 1

		[[helmet.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

