
[hoe]
	enable = true

	[[hoe.attributes]]
		type = "mining_speed"

		[hoe.attributes.eneng]
			enable = true
			value = [3.0, 5.0]

		[[hoe.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 0.5
			speed = 2

		[[hoe.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.1

	[[hoe.attributes]]
		type = "experience_gained"

		[hoe.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[hoe.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.2
			speed = 1

		[[hoe.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

