
[leggings]
	enable = true

	[[leggings.attributes]]
		type = "generic.armor"

		[leggings.attributes.eneng]
			enable = true
			value = [3.0, 5.0]

		[[leggings.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 1.0
			speed = 1

		[[leggings.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[leggings.attributes]]
		type = "generic.armor_toughness"

		[leggings.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[leggings.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 2

		[[leggings.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[leggings.attributes]]
		type = "generic.knockback_resistance"

		[leggings.attributes.eneng]
			enable = true
			value = [0.1, 0.3]

		[[leggings.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.05
			speed = 1

		[[leggings.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[leggings.attributes]]
		type = "generic.movement_speed"

		[leggings.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[leggings.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.02
			speed = 1

		[[leggings.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.01

	[[leggings.attributes]]
		type = "generic.max_health"

		[leggings.attributes.eneng]
			enable = true
			value = [2.0, 4.0]

		[[leggings.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 1.0
			speed = 1

		[[leggings.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

