
[leggings]
	enable = true

	[[leggings.attributes]]
		type = "generic.armor"

		[leggings.attributes.eneng]
			enable = true
			value = [1.5, 2.5]

		[[leggings.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.5
			speed = 1

		[[leggings.attributes.grows]]
			range = [11, -1]
			type = "proportional"
			value = 0.04

	[[leggings.attributes]]
		type = "generic.armor_toughness"

		[leggings.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[leggings.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 2

		[[leggings.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[leggings.attributes]]
		type = "generic.knockback_resistance"

		[leggings.attributes.eneng]
			enable = true
			value = [0.1, 0.3]

		[[leggings.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.05
			speed = 1

		[[leggings.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.02

	[[leggings.attributes]]
		type = "generic.movement_speed"

		[leggings.attributes.eneng]
			enable = true
			value = [0.03, 0.05]

		[[leggings.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.01
			speed = 1

	[[leggings.attributes]]
		type = "generic.max_health"

		[leggings.attributes.eneng]
			enable = true
			value = [1.2, 2.4]

		[[leggings.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 0.6
			speed = 1

		[[leggings.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

