
[pickaxe]
	enable = true

	[[pickaxe.attributes]]
		type = "mining_speed"

		[pickaxe.attributes.eneng]
			enable = true
			value = [0.1, 0.2]

		[[pickaxe.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.1
			speed = 2

	[[pickaxe.attributes]]
		type = "experience_gained"

		[pickaxe.attributes.eneng]
			enable = true
			value = [0.03, 0.07]

		[[pickaxe.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.02
			speed = 1

