
[pickaxe]
	enable = true

	[[pickaxe.attributes]]
		type = "mining_speed"

		[pickaxe.attributes.eneng]
			enable = true
			value = [4.0, 6.0]

		[[pickaxe.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 0.5
			speed = 2

		[[pickaxe.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.1

	[[pickaxe.attributes]]
		type = "experience_gained"

		[pickaxe.attributes.eneng]
			enable = true
			value = [1.0, 2.0]

		[[pickaxe.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.2
			speed = 1

		[[pickaxe.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

