
[shield]
	enable = true

	[[shield.attributes]]
		type = "generic.armor"

		[shield.attributes.eneng]
			enable = true
			value = [5.0, 8.0]

		[[shield.attributes.grows]]
			range = [1, 5]
			type = "fixed"
			value = 1.0
			speed = 1

		[[shield.attributes.grows]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

