
[shield]
	enable = true

	[[shield.attributes]]
		type = "generic.armor"

		[shield.attributes.eneng]
			enable = true
			value = [5.0, 8.0]

		[[shield.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 1.0
			speed = 1

		[[shield.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.05

	[[shield.attributes]]
		type = "generic.knockback_resistance"

		[shield.attributes.eneng]
			enable = true
			value = [0.2, 0.5]

		[[shield.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.05
			speed = 1

		[[shield.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.03

