
[shovel]
	enable = true

	[[shovel.attributes]]
		type = "mining_speed"

		[shovel.attributes.eneng]
			enable = true
			value = [0.1, 0.2]

		[[shovel.attributes.grows]]
			range = [1, 10]
			type = "fixed"
			value = 0.038
			speed = 1

		[[shovel.attributes.grows]]
			range = [11, -1]
			type = "proportional"
			value = 0.05

	[[shovel.attributes]]
		type = "experience_gained"

		[shovel.attributes.eneng]
			enable = true
			value = [0.03, 0.07]

		[[shovel.attributes.grows]]
			range = [1, -1]
			type = "fixed"
			value = 0.02
			speed = 1

