
[sword]
	enable = true

	[[sword.attributes]]
		type = "generic.attack_damage"

		[sword.attributes.eneng]
			enable = true
			value = [4.0, 8.0]

		[[sword.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 1.0
			speed = 1

		[[sword.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.05

	[[sword.attributes]]
		type = "generic.attack_speed"

		[sword.attributes.eneng]
			enable = true
			value = [2.0, 4.0]

		[[sword.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 1

		[[sword.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.03

	[[sword.attributes]]
		type = "life_steal"

		[sword.attributes.eneng]
			enable = true
			value = [0.02, 0.05]

		[[sword.attributes.grow]]
			range = [1, 8]
			type = "fixed"
			value = 0.01
			speed = 1

		[[sword.attributes.grow]]
			range = [9, -1]
			type = "proportional"
			value = 0.01

	[[sword.attributes]]
		type = "crit_chance"

		[sword.attributes.eneng]
			enable = true
			value = [0.05, 0.1]

		[[sword.attributes.grow]]
			range = [1, 7]
			type = "fixed"
			value = 0.02
			speed = 2

		[[sword.attributes.grow]]
			range = [8, -1]
			type = "proportional"
			value = 0.01

	[[sword.attributes]]
		type = "crit_damage"

		[sword.attributes.eneng]
			enable = true
			value = [1.5, 2.0]

		[[sword.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.5
			speed = 1

		[[sword.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.1

	[[sword.attributes]]
		type = "current_hp_damage"

		[sword.attributes.eneng]
			enable = true
			value = [0.03, 0.06]

		[[sword.attributes.grow]]
			range = [1, 10]
			type = "fixed"
			value = 0.01
			speed = 2

		[[sword.attributes.grow]]
			range = [11, -1]
			type = "proportional"
			value = 0.005

	[[sword.attributes]]
		type = "overheal"

		[sword.attributes.eneng]
			enable = true
			value = [0.01, 0.03]

		[[sword.attributes.grow]]
			range = [1, 5]
			type = "fixed"
			value = 0.005
			speed = 1

		[[sword.attributes.grow]]
			range = [6, -1]
			type = "proportional"
			value = 0.002

